name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      id: version
      with:
        major_pattern: "major:"
        minor_pattern: "minor:"
        format: "${major}.${minor}.${patch}+${increment}"
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t santicm23/docker-actions:$NEW_VERSION .
        docker build -t santicm23/docker-actions .
    - name: Push docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push santicm23/docker-actions:$NEW_VERSION
        docker push santicm23/docker-actions
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
